services:
  db:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgre_user
      POSTGRES_PASSWORD: postgre_password
      POSTGRES_DB: elt_pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre_user -d elt_pipeline"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mock_api:
    build:
      context: .
      dockerfile: mock_api/dockerfile
    container_name: mock_api
    ports:
      - "8000:8000"
    environment:
      FAILURE_RATE: "0.05"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_period: 5s
    restart: unless-stopped

  seaweedfs:
    image: chrislusf/seaweedfs-enterprise:4.47
    container_name: seaweedfs
    ports:
      - "9333:9333"
      - "8333:8333"
    volumes:
      - ./seaweedfs/data:/data
    command: server -s3 -dir=/data
    restart: unless-stopped

volumes:
  postgres_data:
