FROM python:3.10-slim

WORKDIR /app

COPY mock_api/requirements.txt ./mock_api/requirements.txt

RUN pip install --no-cache-dir --default-timeout=1000 -r ./mock_api/requirements.txt

COPY mock_api ./mock_api

CMD ["uvicorn", "mock_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
