services:
    db:
      image: postgre:15
      env_file:
        - .env
      enviroment: 
        - POSTGRE_PASSWORD:POSTGRE_PASSWORD
        - POSTGRE_USER:POSTGRE_USER

    mock_api:
      build: ./mock_api
      ports: 
        - 8000:8000
      env_file:
        - .env
      enviroment:
        - API_KEY=API_KEY
      health_check:
        test: ["CMD","curl","-f","http://localhost:8000/health"]
        interval: 10s
        timeout: 5s
        retries: 3
      restart: unless-stopped

    redis:
      build:



